on:
  workflow_call:
    inputs:
      run_command:
        type: string
        required: true

jobs:  
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: test
        run: ${{ inputs.run_command}}