name: root-workflow-call
description: description

inputs:
  run_command:
    description: command to run
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
      
    - name: Setup node  
      uses: actions/setup-node@v3
      with:
        node-version: 16.19.0

    - name: test
      shell: bash
      run: ${{ inputs.run_command}}