name: root-workflow-call
description: description

inputs:
  run_command:
    description: command to run
    required: true

runs:
  using: "composite"
  steps:
    - name: test
      shell: bash
      run: ${{ inputs.run_command}}