name: test
description: description

inputs:
  run_command:
    description: command to run
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      shell: bash
      uses: actions/checkout@v3

    - name: test
      shell: bash
      run: ${{ inputs.run_command}}