name: PR verification

on:
  pull_request:
    paths:
      - README.md

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: |
          cat README.md