name: Test PR verification

on:
  pull_request:


jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    steps:
      - name: Setup jq & awscli
        run: |
          apt update
          apt install -y jq 
          pip install awscli