name: Test PR verification

on:
  pull_request:
    paths:
      - test/*

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    steps:
      - name: Setup jq & awscli
        run: |
          cat ./test/test.md