name: Test PR verification

on:
  pull_request:
    paths:
      - test/*

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: |
          cat ./test/test.md